# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maribel Noguera
email: info@maribelnoguera.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /site-maribelnoguera-com # the subpath of your site, e.g. /blog
url: https://jobace78.github.io # the base hostname & protocol for your site, e.g. http://example.com
## twitter_username: jekyllrb
## github_username:  jekyll

# Build settings
markdown: kramdown
## theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

company_address: C/ Pou Bo 10, 07350, Illes Balears, Spain
company_address_google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12281.020085340102!2d2.8328934670586445!3d39.68896969505078!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1297c41c56759fdf%3A0xe0e606de749a1eef!2s07350%20Binisalem%2C%20Illes%20Balears!5e0!3m2!1ses!2ses!4v1735836338314!5m2!1ses!2ses
company_email: info@maribelnoguera.com
company_feedback_form: https://formspree.io/f/xpwwopeq
company_name: Maribel Noguera
company_phone: +34 696 897 730
facebook_link: https://www.facebook.com/maribelnoguera/
