baseurl: ""
collections:
  services:
    output: true
company_address: Carrer des Pou Bo 10, 07350 Binissalem, Illes Balears, Spain
company_address_google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3070.4123979032324!2d2.8411636761997108!3d39.685430671566486!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1297c14414b0e911%3A0x6b7af02cfcd511ac!2sCarrer%20des%20Pou%20Bo%2C%2010%2C%2007350%20Binissalem%2C%20Illes%20Balears!5e0!3m2!1ses!2ses!4v1740522899554!5m2!1ses!2ses
company_email: info@maribelnoguera.com
company_feedback_form: https://formspree.io/f/xpwwopeq
company_geo_latitude: 39.68543
company_geo_longitude: 2.84116
company_name: Maribel Noguera
company_phone: +34 696 897 730
defaults:
  - scope:
      path: ""
    values:
      lang: es
      locale: es_ES
  - scope:
      path: "ca"
    values:
      lang: ca
      locale: ca_ES
  - scope:
      path: "_services/ca"
    values:
      lang: ca
      locale: ca_ES
  - scope:
      path: ""
      type: services
    values:
      layout: service
      seo:
        type: WebPage
description: >-
  Terapia Gestalt y Coaching en Mallorca. Acompañamiento
  personalizado hacia tu bienestar emocional, presencial y online.
email: info@maribelnoguera.com
exclude:
  - Gemfile
  - Gemfile.lock
  - mise.toml
facebook_link: https://www.facebook.com/calmatumente.terapia
google_analytics_id: G-1WH0W8LPWS
instagram_link: https://www.instagram.com/calmatumente.terapia
lang: es
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
staging: false
title: Maribel Noguera
url: https://www.maribelnoguera.com
whatsapp_link: https://wa.me/34696897730
