[env]
BUNDLE_BIN = "{{ env.HOME }}/.bundles/{{ config_root | basename }}/bin"
BUNDLE_PATH = "{{ env.HOME }}/.bundles/{{ config_root | basename }}"
#
# Notes:
#   - only used when installing gems directly with 'gem install' without bundler, NOT needed for projects with 'Gemfile'...
#
GEM_HOME = "{{ env.HOME }}/.gems/{{ config_root | basename }}"
#
# Notes:
#   - only used when installing gems directly with 'gem install' without bundler, NOT needed for projects with 'Gemfile'...
#
GEM_PATH = "{{ env.HOME }}/.gems/{{ config_root | basename }}"
_BUNDLER_VERSION = "~> 2.4.0"
_MISE_ENV = "{{ config_root | basename }}"
[tasks.clean]
alias = "c"
description = "(bundle) clean"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle clean --force 2> /dev/null || true
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks.doctor]
alias = "d"
description = "doctor"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

cat << EOT

===> BUNDLE_BIN
${BUNDLE_BIN:?}
===> BUNDLE_PATH
${BUNDLE_PATH:?}
===> GEM_HOME (only used when installing gems directly with 'gem install' without bundler, NOT needed for projects with 'Gemfile'...)
${GEM_HOME:?}
===> GEM_PATH (only used when installing gems directly with 'gem install' without bundler, NOT needed for projects with 'Gemfile'...)
${GEM_PATH:?}
===> bundle version
$(bundle --version)
===> gem version
$(gem --version)
===> ruby location
$(command -v ruby)
===> ruby version
$(ruby --version)

EOT
"""
[tasks."gem:cleanup"]
alias = "gc"
description = "(bundle exec) gem cleanup"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec gem cleanup
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks."gem:list"]
alias = "gl"
description = "(bundle exec) gem list"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec gem list
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks.install]
alias = "i"
description = "install"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

mkdir -p {{ env.HOME }}/.bundle
mkdir -p {{ env.HOME }}/.bundles/{{ config_root | basename }}
mkdir -p {{ env.HOME }}/.gem
mkdir -p {{ env.HOME }}/.gems/{{ config_root | basename }}
gem install bundler --no-document --version "${_BUNDLER_VERSION}"
if [ -f Gemfile ]; then
    bundle install
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks."jekyll:build"]
alias = "jb"
description = "(bundle exec) jekyll build"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec jekyll build --config _config.yml --destination _site
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks."jekyll:build-staging"]
alias = "jbs"
description = "(bundle exec) jekyll build staging"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec jekyll build --config _config_staging.yml --destination _site-staging
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks."jekyll:deploy"]
alias = "jd"
description = "(git) commit and push"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

CURRENT_BRANCH="$(git branch --show-current 2> /dev/null || printf '%s' '')"
LIVE_CLONE='{{ config_root }}'
LIVE_URL="$(yq '.url' _config.yml)"
readonly CURRENT_BRANCH LIVE_CLONE LIVE_URL

if [ "${CURRENT_BRANCH}" = 'main' ]; then
    if [ -d "${LIVE_CLONE}/.git" ]; then
        bundle exec jekyll build --config _config.yml --destination _site
        git -C "${LIVE_CLONE}" add --all
        if git -C "${LIVE_CLONE}" diff --cached --quiet main; then
            echo "===> nothing to deploy."
        else
            git -C "${LIVE_CLONE}" commit --message 'WIP' --message "v$(date +%Y%m)" 1> /dev/null
            git -C "${LIVE_CLONE}" fetch origin --prune
            git -C "${LIVE_CLONE}" push --set-upstream origin main
            echo "===> published to '${LIVE_URL:?}'..."
        fi
    else
        echo "'${LIVE_CLONE}' is NOT a git clone, exiting."
        exit 1
    fi
else
    echo "NOT on 'main' branch (current branch: '${CURRENT_BRANCH}'), exiting."
    exit 1
fi
"""
[tasks."jekyll:deploy-staging"]
alias = "jds"
description = "(git) commit and push staging"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

CURRENT_BRANCH="$(git branch --show-current 2> /dev/null || printf '%s' '')"
STAGING_CLONE='../{{ config_root | basename }}-staging'
STAGING_URL="$(yq '.url' _config_staging.yml)$(yq '.baseurl' _config_staging.yml)"
readonly CURRENT_BRANCH STAGING_CLONE STAGING_URL

if [[ "${CURRENT_BRANCH}" == feature/* ]]; then
    if [ -d "${STAGING_CLONE}/.git" ]; then
        bundle exec jekyll build --config _config_staging.yml --destination _site-staging
        touch _site-staging/.nojekyll
        rsync --archive --delete \
            --exclude '.editorconfig' \
            --exclude '.git/' \
            --exclude '.gitignore' \
            --exclude '.idea/' \
            --exclude '.workspaces.conf' \
            _site-staging/ "${STAGING_CLONE}/"
        git -C "${STAGING_CLONE}" add --all
        if git -C "${STAGING_CLONE}" diff --cached --quiet main; then
            echo "===> nothing to deploy."
        else
            git -C "${STAGING_CLONE}" reset --quiet --soft "$(git -C "${STAGING_CLONE}" rev-list --max-parents=0 main | tail -1)"
            git -C "${STAGING_CLONE}" commit --message 'WIP' --message "v$(date +%Y%m)" 1> /dev/null
            git -C "${STAGING_CLONE}" fetch origin --prune
            git -C "${STAGING_CLONE}" push --force --set-upstream origin main
            echo "===> published to '${STAGING_URL:?}'..."
        fi
    else
        echo "'${STAGING_CLONE}' is NOT a git clone, exiting."
        exit 1
    fi
else
    echo "NOT on 'feature/*' branch (current branch: '${CURRENT_BRANCH}'), exiting."
    exit 1
fi
"""
[tasks."jekyll:serve"]
alias = "js"
description = "(bundle exec) jekyll serve"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec jekyll serve --config _config.yml --destination _site
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks."jekyll:serve-staging"]
alias = "jss"
description = "(bundle exec) jekyll serve staging"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle exec jekyll serve --config _config_staging.yml --destination _site-staging
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tasks.prune]
alias = "p"
description = "prune"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

echo "===> cleaning [{{ env.HOME }}/.bundle]..."
rm -rfv {{ env.HOME }}/.bundle
echo "===> cleaning [{{ env.HOME }}/.bundles/{{ config_root | basename }}]..."
rm -rfv {{ env.HOME }}/.bundles/{{ config_root | basename }}
echo "===> cleaning [{{ env.HOME }}/.gem]..."
rm -rfv {{ env.HOME }}/.gem
echo "===> cleaning [{{ env.HOME }}/.gems/{{ config_root | basename }}]..."
rm -rfv {{ env.HOME }}/.gems/{{ config_root | basename }}
"""
[tasks.update]
alias = "u"
description = "(bundle) update"
run = """
#!/usr/bin/env bash

set -e -o pipefail

cd {{ config_root }} || exit 1

if [ -f Gemfile ]; then
    bundle update
else
    echo "'Gemfile' was NOT found, exiting."
    exit 1
fi
"""
[tools]
ruby = "2.7"
yq = "4"
